version: "2"

run:
  timeout: 10m
  concurrency: 2
  tests: true
  build-tags:
    - integration

linters:
  default: standard

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
